apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: micro-prod
type: Opaque
stringData:
  # ===== Database (RDS Postgres) =====
  DB_HOST: django-db.cwjek40uuf89.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: microservices_db
  DB_USER: postgres
  DB_PASSWORD: strongpassword

  # ===== Redis =====
  REDIS_URL: redis://redis:6379/0

  # ===== Django =====
  DJANGO_SECRET_KEY: super-secret-key
