apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: micro-prod
type: Opaque
stringData:
  DB_HOST: your-rds-endpoint.amazonaws.com
  DB_NAME: microservices_db
  DB_USER: postgres
  DB_PASSWORD: strongpassword
  REDIS_URL: redis://redis:6379/0
  DJANGO_SECRET_KEY: super-secret-key
