# apiVersion: v1
# kind: Secret
# metadata:
#   name: backend-secrets
#   namespace: micro-prod
# type: Opaque
# stringData:
#   # ===== Database (RDS Postgres) =====
#   DB_HOST: django-db.cwjek40uuf89.us-east-1.rds.amazonaws.com
#   DB_PORT: "5432"
#   DB_NAME: djangodb
#   DB_USER: djangoadmin
#   DB_PASSWORD: django123!

#   # ===== Redis =====
#   REDIS_URL: redis://redis:6379/0

#   # ===== Django =====
#   DJANGO_SECRET_KEY: super-secret-key
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: micro-prod
type: Opaque
stringData:
  # ===== Database (RDS Postgres) =====
  DB_HOST: django-db.cwjek40uuf89.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: djangodb
  DB_USER: djangoadmin
  DB_PASSWORD: django123!

  # ===== Redis =====
  REDIS_URL: redis://redis:6379/0

  # ===== Django =====
  DJANGO_SECRET_KEY: super-secret-key

  # âœ… FINAL FIX (IMPORTANT)
  ALLOWED_HOSTS: a0713f02f58544f61927db6623c89f5d-519cc3887cdd3603.elb.us-east-1.amazonaws.com,backend
