apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: micro-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ORG/REPO.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: micro-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
